### ISSUE TITLE
Documentation/tut/microsites

### ISSUE THREAD

**Issue by denisrosset** [non/spire#702]
I am collecting here issues/PRs related to documentation/tut/microsites.

Currently, we have upgraded your build to SBT 1.0, but microsites is not yet compatible with that release.

#553 Subtyping graphs in documentation
#607 @tixxit PR to introduce microsites

However, we started checking our documentation with `tut` (  #680 #692  ). We should consider:

- [ ] updating the README.md automatically as part of a SBT task
- [ ] splitting the documentation in easily digestible pieces (ala cats: typeclasses, data types, ...)
- [ ] when microsites is ready (or if we can use another solution), introduce a website for Spire

We should document the motivation of default instances as well (for example, lattices for Int/Short/Byte...)

**Comment by denisrosset** [comment]
@non: microsites should actually be compatible with SBT 1.0. Algebra has migrated.

**Comment by denisrosset** [comment]
Main headings

- Getting started / contribute / community / license (main page)
- Number types
- Algebraic structures / Type classes
-- Syntax summary
-- Semigroup/Monoid/Group
-- Additive/Multiplicative S/M/G
-- Eq/PartialOrder/Order/Signed/TruncatedDivision
-- CRing, UFD, GCDRing, EuclideanRing, Field
-- NRoot, Trig
-- Noncommutative rings, DivisionRing
-- Modules/VectorSpace/Algebra
-- Actions
- Algorithms
-- Sorting
-- Selection
-- Searching
- Miscellany

**Comment by denisrosset** [comment]
See #760
